name: CI

# Controls when the workflow will run
on: [push, workflow_dispatch]
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Show where is triggered from
        run: |
          echo grgry ci/cd pipeline is triggered.

  build:
    needs:
      - pre
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  semantic-release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GHA_GRGRY }}
